/*
 * File: app/view/procesos/prod/NewPro.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.procesos.prod.NewPro', {
    extend: 'Ext.window.Window',
    alias: 'widget.newpro',

    requires: [
        'app.view.procesos.prod.NewProViewModel',
        'app.view.std.form.Ent',
        'app.view.std.form.Txt',
        'app.view.std.form.TxtArea',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'procesos.prod.newpro'
    },
    modal: true,
    width: 669,
    title: 'Nuevo/Editar',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'ent',
                    hidden: true,
                    labelWidth: 100,
                    name: 'id'
                },
                {
                    xtype: 'txt',
                    fieldLabel: 'Nombre',
                    labelWidth: 100,
                    name: 'name',
                    allowBlank: false
                },
                {
                    xtype: 'txtArea',
                    fieldLabel: 'Descripción',
                    name: 'description',
                    allowBlank: false
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var win  = button.up('window'),
                            frm  = win.down('form'),
                            val  = frm.getValues(),
                            ajax = app.controller.std.Glob.ajax,
                            url	 = 'products';

                        if(frm.isValid()){
                            var metodo = 'POST';
                            if(val.id>0){
                                metodo = 'PUT';
                                url= url+'/'+val.id;
                            }

                            var json = ajax(metodo, url,val);
                            if(json.success){
                                Ext.Msg.alert('Aviso','Almacenamiento correcto');
                                win.close();
                            }
                        }else{
                            Ext.Msg.alert('Aviso','Antes de continuar debe completar los datos obligatorios');
                        }

                    },
                    text: 'Aceptar'
                }
            ]
        }
    ]

});