/*
 * File: app/view/std/Salir.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.std.Salir', {
    extend: 'Ext.container.Container',
    alias: 'widget.salir',

    requires: [
        'app.view.std.SalirViewModel'
    ],

    viewModel: {
        type: 'salir'
    },
    layout: 'fit',
    defaultListenerScope: true,

    listeners: {
        afterlayout: 'onContainerAfterLayout'
    },

    onContainerAfterLayout: function(container, layout, eOpts) {
        Ext.Msg.show({
            title:'Salir',
            msg: '¿ Realmente desea Salir ?',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            left:50,
            top:50,
            fn: function(btn){
                if (btn === "yes"){

                    Ext.Ajax.request({
                        url: '../Engine',
                        scope : this,

                        params: {
                            paquete: 'std',
                            clase: 'Login',
                            metodo: 'salir'
                        },

                        headers: {
                            'Accept': 'application/json'
                        },

                        success: function(response) {
                            Ext.Msg.show({
                                title:'Salir',
                                msg: 'Sesíon finalizada con éxito!',
                                icon:  Ext.Msg.INFO,
                                buttons :Ext.Msg.OK,
                                fn: function(btn){
                                    if (btn === "ok"){

                                        location.reload(true);

                                    }
                                }

                            });
                        },
                        failure: function(response) {
                            Ext.Msg.show({
                                title :'ERROR ',
                                msg : 'Se ha presentado un error en el sistema!',
                                icon :Ext.Msg.ERROR,

                            });
                        }
                    });

                }

            } });




    }

});